package itmo.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ShipService", targetNamespace = "http://webservice.itmo/", wsdlLocation = "http://localhost:8080/ShipService?wsdl")
public class ShipService
        extends Service {

    private final static URL SHIPWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPWEBSERVICESERVICE_EXCEPTION;
    private final static QName SHIPWEBSERVICESERVICE_QNAME = new QName("http://webservice.itmo/", "ShipService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ShipService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPWEBSERVICESERVICE_WSDL_LOCATION = url;
        SHIPWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ShipService() {
        super(__getWsdlLocation(), SHIPWEBSERVICESERVICE_QNAME);
    }

    public ShipService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPWEBSERVICESERVICE_QNAME, features);
    }

    public ShipService(URL wsdlLocation) {
        super(wsdlLocation, SHIPWEBSERVICESERVICE_QNAME);
    }

    public ShipService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPWEBSERVICESERVICE_QNAME, features);
    }

    public ShipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ShipWebService
     */
    @WebEndpoint(name = "ShipWebServicePort")
    public ShipWebService getShipWebServicePort() {
        return super.getPort(new QName("http://webservice.itmo/", "ShipWebServicePort"), ShipWebService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ShipWebService
     */
    @WebEndpoint(name = "ShipWebServicePort")
    public ShipWebService getShipWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.itmo/", "ShipWebServicePort"), ShipWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPWEBSERVICESERVICE_EXCEPTION != null) {
            throw SHIPWEBSERVICESERVICE_EXCEPTION;
        }
        return SHIPWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
